// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5147.RobotAttempt1;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainfrontLeft;
    public static CANTalon driveTrainfrontRight;
    public static CANTalon driveTrainbackRight;
    public static CANTalon driveTrainbackLeft;
    public static RobotDrive driveTrainmainDrive;
    public static SpeedController ballPickerUpperpickerUpperSpark;
    public static SpeedController climberclimberSpark;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainfrontLeft = new CANTalon(0);
        LiveWindow.addActuator("DriveTrain", "frontLeft", driveTrainfrontLeft);
        
        driveTrainfrontRight = new CANTalon(1);
        LiveWindow.addActuator("DriveTrain", "frontRight", driveTrainfrontRight);
        
        driveTrainbackRight = new CANTalon(2);
        LiveWindow.addActuator("DriveTrain", "backRight", driveTrainbackRight);
        
        driveTrainbackLeft = new CANTalon(3);
        LiveWindow.addActuator("DriveTrain", "backLeft", driveTrainbackLeft);
        
        driveTrainmainDrive = new RobotDrive(driveTrainfrontLeft, driveTrainbackLeft,
              driveTrainfrontRight, driveTrainbackRight);
        
        driveTrainmainDrive.setSafetyEnabled(true);
        driveTrainmainDrive.setExpiration(0.1);
        driveTrainmainDrive.setSensitivity(0.5);
        driveTrainmainDrive.setMaxOutput(1.0);

        ballPickerUpperpickerUpperSpark = new Spark(1);
        LiveWindow.addActuator("ballPickerUpper", "pickerUpperSpark", (Spark) ballPickerUpperpickerUpperSpark);
        
        climberclimberSpark = new Spark(0);
        LiveWindow.addActuator("Climber", "climberSpark", (Spark) climberclimberSpark);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
